
TEST_OUTPUT = {'current_observation': {'precip_today_string': '0.00 in (0 mm)',
               'image': {'url': 'http://icons.wxug.com/graphics/wu2/logo_130x80.png',
               'title': 'Weather Underground', 'link': 'http://www.wunderground.com'},
               'feelslike_c': '28', 'temperature_string': '86.5 F (30.3 C)',
               'local_tz_long': 'America/Los_Angeles',
               'wind_kph': 4.3,
               'precip_1hr_string': '0.00 in ( 0 mm)',
               'precip_1hr_metric': ' 0',
               'heat_index_string': '83 F (28 C)',
               'wind_degrees': 324,
               'wind_dir': 'NW', 'local_tz_short': 'PDT',
               'display_location': {'city': 'Seattle', 'elevation': '63.00000000',
               'country': 'US',
               'zip': '98101',
               'wmo': '99999',
               'full': 'Seattle, WA',
                'state': 'WA',
                'state_name': 'Washington',
                'country_iso3166': 'US',
                'magic': '1',
                'longitude': '-122.33325958',
                'latitude': '47.61167908'},
                'station_id': 'KWASEATT398',
                'nowcast': '',
                'local_time_rfc822': 'Mon, 02 May 2016 16:14:35 -0700',
                'history_url': 'http://www.wunderground.com/weatherstation/WXDailyHistory.asp?ID=KWASEATT398',
                'observation_time': 'Last Updated on May 2, 4:14 PM PDT',
                'dewpoint_f': 41,
                'heat_index_f': 83,
                'heat_index_c': 28,
                'dewpoint_string': '41 F (5 C)',
                'ob_url': 'http://www.wunderground.com/cgi-bin/findweather/getForecast?query=47.612675,-122.347694',
                'wind_string': 'From the NW at 2.7 MPH Gusting to 4.9 MPH',
                'forecast_url': 'http://www.wunderground.com/US/WA/Seattle.html',
                'wind_gust_mph': '4.9',
                'visibility_km': '16.1',
                'windchill_f': 'NA', 'precip_today_metric': '0', 'pressure_mb': '1012', 'windchill_c': 'NA', 'pressure_in': '29.88', 'observation_epoch': '1462230862', 'feelslike_string': '83 F (28 C)', 'UV': '3.0', 'observation_time_rfc822': 'Mon, 02 May 2016 16:14:22 -0700', 'weather': 'Partly Cloudy', 'icon': 'partlycloudy', 'dewpoint_c': 5, 'temp_c': 30.3, 'temp_f': 86.5, 'visibility_mi': '10.0', 'relative_humidity': '20%', 'estimated': {}, 'feelslike_f': '83', 'pressure_trend': '-', 'local_tz_offset': '-0700', 'local_epoch': '1462230875', 'precip_today_in': '0.00', 'icon_url': 'http://icons.wxug.com/i/c/k/partlycloudy.gif', 'observation_location': {'full': 'Belltown, Seattle, Washington', 'city': 'Belltown, Seattle', 'state': 'Washington', 'country_iso3166': 'US', 'elevation': '135 ft', 'longitude': '-122.347694', 'country': 'US', 'latitude': '47.612675'}, 'wind_gust_kph': '7.9', 'precip_1hr_in': '0.00', 'solarradiation': '690', 'windchill_string': 'NA', 'wind_mph': 2.7}, 'response': {'version': '0.1', 'features': {'conditions': 1}, 'termsofService': 'http://www.wunderground.com/weather/api/d/terms.html'}}
