NPR_RESPONSE = {'list': {'link': [{'$text': 'http://api.npr.org/query?id=1004&meta=inherit&apiKey=MDI0MTM4NTA1MDE0NjIyMDU0OTM1ZDUwNQ000',
    'type': 'api'},
   {'$text': 'http://www.npr.org/sections/world/?ft=nprml&f=1004',
    'type': 'html'}],
  'miniTeaser': {},
  'story': [{'id': '476873854',
    'link': [{'$text': 'http://www.npr.org/2016/05/05/476873854/newly-released-documents-detail-traumas-of-chinas-cultural-revolution?ft=nprml&f=1004',
      'type': 'html'},
     {'$text': 'http://api.npr.org/query?id=476873854&apiKey=MDI0MTM4NTA1MDE0NjIyMDU0OTM1ZDUwNQ000',
      'type': 'api'},
     {'$text': 'http://n.pr/1T0ysWx', 'type': 'short'}],
    'title': {'$text': "Newly Released Documents Detail Traumas Of China's Cultural Revolution"}},
   {'id': '476881227',
    'link': [{'$text': 'http://www.npr.org/sections/thetwo-way/2016/05/05/476881227/as-u-k-voters-head-to-polls-all-eyes-are-on-londons-mayoral-race?ft=nprml&f=1004',
      'type': 'html'},
     {'$text': 'http://api.npr.org/query?id=476881227&apiKey=MDI0MTM4NTA1MDE0NjIyMDU0OTM1ZDUwNQ000',
      'type': 'api'},
     {'$text': 'http://n.pr/1T0Fafc', 'type': 'short'}],
    'title': {'$text': "As U.K. Voters Head To Polls, All Eyes Are On London's Mayoral Race"}},
   {'id': '476902856',
    'link': [{'$text': 'http://www.npr.org/sections/thetwo-way/2016/05/05/476902856/-i-m-sorry-says-man-who-claimed-to-be-bitcoin-s-creator?ft=nprml&f=1004',
      'type': 'html'},
     {'$text': 'http://api.npr.org/query?id=476902856&apiKey=MDI0MTM4NTA1MDE0NjIyMDU0OTM1ZDUwNQ000',
      'type': 'api'},
     {'$text': 'http://n.pr/1T0TAMg', 'type': 'short'}],
    'title': {'$text': "'I'm Sorry,' Says Man Who Claimed To Be Bitcoin's Creator"}},
   {'id': '476871160',
    'link': [{'$text': 'http://www.npr.org/sections/thetwo-way/2016/05/05/476871160/u-s-army-captain-is-suing-obama-over-legality-of-the-war-against-isis?ft=nprml&f=1004',
      'type': 'html'},
     {'$text': 'http://api.npr.org/query?id=476871160&apiKey=MDI0MTM4NTA1MDE0NjIyMDU0OTM1ZDUwNQ000',
      'type': 'api'},
     {'$text': 'http://n.pr/1T0wRzO', 'type': 'short'}],
    'title': {'$text': 'U.S. Army Captain Is Suing Obama Over Legality Of The War Against ISIS'}},
   {'id': '476876371',
    'link': [{'$text': 'http://www.npr.org/sections/thesalt/2016/05/05/476876371/u-s-to-ship-peanuts-to-feed-haitian-kids-aid-groups-say-this-is-wrong?ft=nprml&f=1004',
      'type': 'html'},
     {'$text': 'http://api.npr.org/query?id=476876371&apiKey=MDI0MTM4NTA1MDE0NjIyMDU0OTM1ZDUwNQ000',
      'type': 'api'},
     {'$text': 'http://n.pr/1T0AG8c', 'type': 'short'}],
    'title': {'$text': "U.S. To Ship Peanuts To Feed Haitian Kids; Aid Groups Say 'This Is Wrong'"}},
   {'id': '475928020',
    'link': [{'$text': 'http://www.npr.org/sections/parallels/2016/05/05/475928020/why-afghanistan-is-once-again-on-the-brink?ft=nprml&f=1004',
      'type': 'html'},
     {'$text': 'http://api.npr.org/query?id=475928020&apiKey=MDI0MTM4NTA1MDE0NjIyMDU0OTM1ZDUwNQ000',
      'type': 'api'},
     {'$text': 'http://n.pr/1SKOLXo', 'type': 'short'}],
    'title': {'$text': 'Why Afghanistan Is Once Again On The Brink'}},
   {'id': '476856576',
    'link': [{'$text': 'http://www.npr.org/sections/thetwo-way/2016/05/05/476856576/turkeys-prime-minister-to-step-down-as-president-erdogan-pushes-for-more-power?ft=nprml&f=1004',
      'type': 'html'},
     {'$text': 'http://api.npr.org/query?id=476856576&apiKey=MDI0MTM4NTA1MDE0NjIyMDU0OTM1ZDUwNQ000',
      'type': 'api'},
     {'$text': 'http://n.pr/1SQNdc9', 'type': 'short'}],
    'title': {'$text': "Turkey's Prime Minister To Step Down As President Erdogan Pushes For More Power"}},
   {'id': '476854976',
    'link': [{'$text': 'http://www.npr.org/sections/thetwo-way/2016/05/05/476854976/alberta-wildfire-evacuees-ordered-to-move-again-blaze-destroys-1-600-buildings?ft=nprml&f=1004',
      'type': 'html'},
     {'$text': 'http://api.npr.org/query?id=476854976&apiKey=MDI0MTM4NTA1MDE0NjIyMDU0OTM1ZDUwNQ000',
      'type': 'api'},
     {'$text': 'http://n.pr/1SQJueB', 'type': 'short'}],
    'title': {'$text': 'Alberta Wildfire Evacuees Ordered To Move Again; Blaze Destroys 1,600 Buildings'}},
   {'id': '476775640',
    'link': [{'$text': 'http://www.npr.org/sections/thetwo-way/2016/05/04/476775640/syrian-army-declares-48-hour-truce-after-intense-fighting-in-aleppo?ft=nprml&f=1004',
      'type': 'html'},
     {'$text': 'http://api.npr.org/query?id=476775640&apiKey=MDI0MTM4NTA1MDE0NjIyMDU0OTM1ZDUwNQ000',
      'type': 'api'},
     {'$text': 'http://n.pr/1TmTqM5', 'type': 'short'}],
    'title': {'$text': 'Syrian Army Declares 48-Hour Truce After Intense Fighting In Aleppo'}},
   {'id': '476779229',
    'link': [{'$text': 'http://www.npr.org/sections/thetwo-way/2016/05/04/476779229/dot-announces-recall-of-up-to-40-million-more-takata-air-bag-inflators?ft=nprml&f=1004',
      'type': 'html'},
     {'$text': 'http://api.npr.org/query?id=476779229&apiKey=MDI0MTM4NTA1MDE0NjIyMDU0OTM1ZDUwNQ000',
      'type': 'api'},
     {'$text': 'http://n.pr/1TmZ0OF', 'type': 'short'}],
    'title': {'$text': 'DOT Announces Recall Of Up To 40 Million More Takata Air Bag Inflators '}}],
  'teaser': {'$text': 'NPR world news, international art and culture, world business and financial markets, world economy, and global trends in health, science and technology. Subscribe to the World Story of the Day podcast and RSS feed.'},
  'title': {'$text': 'NPR Topics: World'}},
 'version': '0.94'}

NPR_JSON = '{"headlines": [{"title": "Leicester City Soccer Club Ends Miracle Season With Premier League Title"}, {"title": "As Europe Closes Door To Refugees, 2 Fathers In Greece Face Tough Choices"}, {"title": "Religious Freedom Faces \'Serious And Sustained Assault\' Around The World"}, {"title": "Puerto Rico Defaults On $422 Million Debt Payment"}, {"title": "In Iraq, Sectarian Militias Threaten To Distract From Fight Against ISIS"}, {"title": "Protesters Rush Parliament Inside Baghdad\'s Green Zone"}, {"title": "Starbucks And Steel: The Divergent Directions Of China\'s Economy"}, {"title": "The Man At The Center Of Iraq\'s Political Storm"}, {"title": "CIA \'Live Tweets\' Bin Laden Raid On 5th Anniversary"}, {"title": "Australian Man Says He Is Bitcoin\'s Founder"}]}'

NPR_DICT = {'headlines': [{'title': "Newly Released Documents Detail Traumas Of China's Cultural Revolution"},
  {'title': "As U.K. Voters Head To Polls, All Eyes Are On London's Mayoral Race"},
  {'title': "'I'm Sorry,' Says Man Who Claimed To Be Bitcoin's Creator"},
  {'title': 'U.S. Army Captain Is Suing Obama Over Legality Of The War Against ISIS'},
  {'title': "U.S. To Ship Peanuts To Feed Haitian Kids; Aid Groups Say 'This Is Wrong'"},
  {'title': 'Why Afghanistan Is Once Again On The Brink'},
  {'title': "Turkey's Prime Minister To Step Down As President Erdogan Pushes For More Power"},
  {'title': 'Alberta Wildfire Evacuees Ordered To Move Again; Blaze Destroys 1,600 Buildings'},
  {'title': 'Syrian Army Declares 48-Hour Truce After Intense Fighting In Aleppo'},
  {'title': 'DOT Announces Recall Of Up To 40 Million More Takata Air Bag Inflators '}]}
