NPR_RESPONSE = {'list': {'link': [{'$text': 'http://api.npr.org/query?id=1004&meta=inherit&apiKey=MDI0MTM4NTA1MDE0NjIyMDU0OTM1ZDUwNQ000',
    'type': 'api'},
   {'$text': 'http://www.npr.org/sections/world/?ft=nprml&f=1004',
    'type': 'html'}],
  'miniTeaser': {},
  'story': [{'id': '476498736',
    'link': [{'$text': 'http://www.npr.org/2016/05/02/476498736/leicester-city-soccer-club-ends-miracle-season-with-premier-league-title?ft=nprml&f=1004',
      'type': 'html'},
     {'$text': 'http://api.npr.org/query?id=476498736&apiKey=MDI0MTM4NTA1MDE0NjIyMDU0OTM1ZDUwNQ000',
      'type': 'api'},
     {'$text': 'http://n.pr/1QOckdm', 'type': 'short'}],
    'title': {'$text': 'Leicester City Soccer Club Ends Miracle Season With Premier League Title'}},
   {'id': '476498715',
    'link': [{'$text': 'http://www.npr.org/2016/05/02/476498715/as-europe-closes-door-to-refugees-2-fathers-in-greece-face-tough-choices?ft=nprml&f=1004',
      'type': 'html'},
     {'$text': 'http://api.npr.org/query?id=476498715&apiKey=MDI0MTM4NTA1MDE0NjIyMDU0OTM1ZDUwNQ000',
      'type': 'api'},
     {'$text': 'http://n.pr/1QOckdg', 'type': 'short'}],
    'title': {'$text': 'As Europe Closes Door To Refugees, 2 Fathers In Greece Face Tough Choices'}},
   {'id': '476498707',
    'link': [{'$text': 'http://www.npr.org/2016/05/02/476498707/religious-freedom-faces-serious-and-sustained-assault-around-the-world?ft=nprml&f=1004',
      'type': 'html'},
     {'$text': 'http://api.npr.org/query?id=476498707&apiKey=MDI0MTM4NTA1MDE0NjIyMDU0OTM1ZDUwNQ000',
      'type': 'api'},
     {'$text': 'http://n.pr/1QOckde', 'type': 'short'}],
    'title': {'$text': "Religious Freedom Faces 'Serious And Sustained Assault' Around The World"}},
   {'id': '476498679',
    'link': [{'$text': 'http://www.npr.org/2016/05/02/476498679/puerto-rico-defaults-on-422-million-debt-payment?ft=nprml&f=1004',
      'type': 'html'},
     {'$text': 'http://api.npr.org/query?id=476498679&apiKey=MDI0MTM4NTA1MDE0NjIyMDU0OTM1ZDUwNQ000',
      'type': 'api'},
     {'$text': 'http://n.pr/1QOcjWU', 'type': 'short'}],
    'title': {'$text': 'Puerto Rico Defaults On $422 Million Debt Payment'}},
   {'id': '476498672',
    'link': [{'$text': 'http://www.npr.org/2016/05/02/476498672/in-iraq-sectarian-militias-threaten-to-distract-from-fight-against-isis?ft=nprml&f=1004',
      'type': 'html'},
     {'$text': 'http://api.npr.org/query?id=476498672&apiKey=MDI0MTM4NTA1MDE0NjIyMDU0OTM1ZDUwNQ000',
      'type': 'api'},
     {'$text': 'http://n.pr/1QOchyg', 'type': 'short'}],
    'title': {'$text': 'In Iraq, Sectarian Militias Threaten To Distract From Fight Against ISIS'}},
   {'id': '476498665',
    'link': [{'$text': 'http://www.npr.org/2016/05/02/476498665/protesters-rush-parliament-inside-baghdads-green-zone?ft=nprml&f=1004',
      'type': 'html'},
     {'$text': 'http://api.npr.org/query?id=476498665&apiKey=MDI0MTM4NTA1MDE0NjIyMDU0OTM1ZDUwNQ000',
      'type': 'api'},
     {'$text': 'http://n.pr/1QOcjWO', 'type': 'short'}],
    'title': {'$text': "Protesters Rush Parliament Inside Baghdad's Green Zone"}},
   {'id': '476460617',
    'link': [{'$text': 'http://www.npr.org/sections/parallels/2016/05/02/476460617/starbucks-and-steel-the-divergent-directions-of-chinas-economy?ft=nprml&f=1004',
      'type': 'html'},
     {'$text': 'http://api.npr.org/query?id=476460617&apiKey=MDI0MTM4NTA1MDE0NjIyMDU0OTM1ZDUwNQ000',
      'type': 'api'},
     {'$text': 'http://n.pr/1QNyMDr', 'type': 'short'}],
    'title': {'$text': "Starbucks And Steel: The Divergent Directions Of China's Economy"}},
   {'id': '476445162',
    'link': [{'$text': 'http://www.npr.org/sections/parallels/2016/05/02/476445162/the-man-at-the-center-of-iraqs-political-storm?ft=nprml&f=1004',
      'type': 'html'},
     {'$text': 'http://api.npr.org/query?id=476445162&apiKey=MDI0MTM4NTA1MDE0NjIyMDU0OTM1ZDUwNQ000',
      'type': 'api'},
     {'$text': 'http://n.pr/1QNho1w', 'type': 'short'}],
    'title': {'$text': "The Man At The Center Of Iraq's Political Storm"}},
   {'id': '476438422',
    'link': [{'$text': 'http://www.npr.org/sections/thetwo-way/2016/05/02/476438422/cia-live-tweets-bin-laden-raid-on-5th-anniversary?ft=nprml&f=1004',
      'type': 'html'},
     {'$text': 'http://api.npr.org/query?id=476438422&apiKey=MDI0MTM4NTA1MDE0NjIyMDU0OTM1ZDUwNQ000',
      'type': 'api'},
     {'$text': 'http://n.pr/1TFB8J5', 'type': 'short'}],
    'title': {'$text': "CIA 'Live Tweets' Bin Laden Raid On 5th Anniversary"}},
   {'id': '476435109',
    'link': [{'$text': 'http://www.npr.org/2016/05/02/476435109/australian-man-says-he-is-bitcoins-founder?ft=nprml&f=1004',
      'type': 'html'},
     {'$text': 'http://api.npr.org/query?id=476435109&apiKey=MDI0MTM4NTA1MDE0NjIyMDU0OTM1ZDUwNQ000',
      'type': 'api'},
     {'$text': 'http://n.pr/1TfmMw4', 'type': 'short'}],
    'title': {'$text': "Australian Man Says He Is Bitcoin's Founder"}}],
  'teaser': {'$text': 'NPR world news, international art and culture, world business and financial markets, world economy, and global trends in health, science and technology. Subscribe to the World Story of the Day podcast and RSS feed.'},
  'title': {'$text': 'NPR Topics: World'}},
 'version': '0.94'}

NPR_JSON = '{"headlines": [{"title": "Leicester City Soccer Club Ends Miracle Season With Premier League Title"}, {"title": "As Europe Closes Door To Refugees, 2 Fathers In Greece Face Tough Choices"}, {"title": "Religious Freedom Faces \'Serious And Sustained Assault\' Around The World"}, {"title": "Puerto Rico Defaults On $422 Million Debt Payment"}, {"title": "In Iraq, Sectarian Militias Threaten To Distract From Fight Against ISIS"}, {"title": "Protesters Rush Parliament Inside Baghdad\'s Green Zone"}, {"title": "Starbucks And Steel: The Divergent Directions Of China\'s Economy"}, {"title": "The Man At The Center Of Iraq\'s Political Storm"}, {"title": "CIA \'Live Tweets\' Bin Laden Raid On 5th Anniversary"}, {"title": "Australian Man Says He Is Bitcoin\'s Founder"}]}'
