# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 00:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PXLBoardModel_1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mlb', models.BooleanField()),
                ('nfl', models.BooleanField()),
                ('nhl', models.BooleanField()),
                ('headlines', models.BooleanField()),
                ('weather', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='PXLBoardModel_2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mlb', models.BooleanField()),
                ('nfl', models.BooleanField()),
                ('nhl', models.BooleanField()),
                ('headlines', models.BooleanField()),
                ('weather', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='PXLBoardModel_3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mlb', models.BooleanField()),
                ('nfl', models.BooleanField()),
                ('nhl', models.BooleanField()),
                ('headlines', models.BooleanField()),
                ('weather', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=255)),
                ('pxlboard_1', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pxl.PXLBoardModel_1')),
                ('pxlboard_2', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pxl.PXLBoardModel_2')),
                ('pxlboard_3', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pxl.PXLBoardModel_3')),
            ],
        ),
    ]
