# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 18:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PXLBoardModel_1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mlb', models.BooleanField()),
                ('nfl', models.BooleanField()),
                ('nhl', models.BooleanField()),
                ('headlines', models.BooleanField()),
                ('weather', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='PXLBoardModel_2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mlb', models.BooleanField()),
                ('nfl', models.BooleanField()),
                ('nhl', models.BooleanField()),
                ('headlines', models.BooleanField()),
                ('weather', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='PXLBoardModel_3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mlb', models.BooleanField()),
                ('nfl', models.BooleanField()),
                ('nhl', models.BooleanField()),
                ('headlines', models.BooleanField()),
                ('weather', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pxlboard_1', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pxl.PXLBoardModel_1')),
                ('pxlboard_2', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pxl.PXLBoardModel_2')),
                ('pxlboard_3', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pxl.PXLBoardModel_3')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
