# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 20:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pxl', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='pxlboard_1',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='pxlboard_2',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='pxlboard_3',
        ),
        migrations.AddField(
            model_name='pxlboardmodel_1',
            name='owner',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pxlboardmodel_2',
            name='owner',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pxlboardmodel_3',
            name='owner',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
