# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-04 17:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pxl', '0002_auto_20160503_2021'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PXLBoardModel_1',
            new_name='PXLBoardModel',
        ),
        migrations.RemoveField(
            model_name='pxlboardmodel_2',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='pxlboardmodel_3',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='user',
        ),
        migrations.DeleteModel(
            name='PXLBoardModel_2',
        ),
        migrations.DeleteModel(
            name='PXLBoardModel_3',
        ),
        migrations.DeleteModel(
            name='UserModel',
        ),
    ]
